### ISSUE TITLE
 Permission issues when downloading Ansible repo as a zip file

### ISSUE THREAD

**Issue by roelbaka** [ryreitsma/ansible-js-services-macbook#1]
When I start with a fresh macbook and download this script as a zip file from github I get the following 2 issues:

The write permissions on the hosts file are wrong. 

```
ERROR: The file hosts is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x hosts`.
```

Because github is an unknown hostkey.

```
failed: [127.0.0.1] => (item=puppet-coolblue-e-commerce-platform) => {"failed": true, "item": "puppet-coolblue-e-commerce-platform"}
msg: github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module
```

**Comment by ryreitsma** [comment]
I don't think I can support a zip download if that fucks up the file permissions. I've changed the README to include a step 'Clone the git repository', to (hopefully) prevent others to run into this issue.

Thanx for reporting the issue.
